services:
  paligemma-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=google/paligemma2-3b-mix-448
      - MODELS_DIR=/app/models
    secrets:
      - hf_token
    volumes:
      - ./models:/app/models
      - $HOME/.cache/huggingface/hub:/app/models/huggingface:ro
    restart: unless-stopped

secrets:
  hf_token:
    file: $HOME/.cache/huggingface/token
