services:
  paligemma-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MODEL_ID=google/paligemma2-3b-mix-448
      - MODELS_DIR=/app/models
    volumes:
      - ./models:/app/models
      - $HOME/.cache/huggingface/hub:/app/models/huggingface
    restart: unless-stopped
